baseurl = "/"
title = "Bushwick Eco Initiatives Website"
author = "John Desmond"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Bushwick Eco Initiatives"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "Sign Up For Composting"
    url = "https://dsny.force.com/curbsidecomposting/s/"
    weight = 4
